# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_notes',
            field=models.CharField(default='', max_length=300, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='learned',
            field=models.CharField(default='', max_length=300, verbose_name='学到知识'),
        ),
    ]
